Move contributed ccl/ccl64 shell scripts to contrib/rittweiler.  Revert to pre-contributed (simpler, less flexible) versions in scripts, both to avoid issues with platforms (Solaris 10) where /bin/sh doesn't refer to a POSIX shell and to avoid the need for documentation changes.

diff --git a/contrib/rittweiler/ccl b/contrib/rittweiler/ccl
--- a/contrib/rittweiler/ccl
+++ b/contrib/rittweiler/ccl
@@ -1,12 +1,35 @@
 #!/bin/sh
 #
 # Change the definition of CCL_DEFAULT_DIRECTORY below to refer to
-# your OpenMCL installation directory.  
+# your Clozure CL installation directory.  
 # Any definition of CCL_DEFAULT_DIRECTORY already present in the environment 
 # takes precedence over definitions made below.
 
+probe()
+{
+    if [ -e "$1"  -a  -e "$1/scripts/ccl" ]; then
+        CCL_DEFAULT_DIRECTORY="$1"
+    fi
+}
+
+if [ -z "$CCL_DEFAULT_DIRECTORY"  -a  -n "`which readlink`" ]; then
+    dir="`readlink $0`"
+    probe "${dir%/scripts/ccl}"
+fi
+
 if [ -z "$CCL_DEFAULT_DIRECTORY" ]; then
-  CCL_DEFAULT_DIRECTORY=/usr/local/src/ccl
+    probe "`pwd`"
+fi
+
+if [ -z "$CCL_DEFAULT_DIRECTORY" ]; then
+    probe "/usr/local/src/ccl"
+fi
+
+if [ -z "$CCL_DEFAULT_DIRECTORY" ]; then
+    echo "Can't find CCL directory.  Please edit $0 or"
+    echo "set the environment variable CCL_DEFAULT_DIRECTORY"
+    echo "and try again."
+    exit 1
 fi
 
 export CCL_DEFAULT_DIRECTORY
@@ -16,7 +39,7 @@ export CCL_DEFAULT_DIRECTORY
 
 DD=${CCL_DEFAULT_DIRECTORY}
 
-# If you don't want to guess the name of the OpenMCL kernel on
+# If you don't want to guess the name of the Clozure CL kernel on
 # every invocation (or if you want to use a kernel with a
 # non-default name), you might want to uncomment and change
 # the following line:
